### ISSUE TITLE
Some species (species not involved in rate equations?) aren't recorded

### ISSUE THREAD

**Issue by jonrkarr** [PySCeS/pysces#57]
Since there doesn't appear to be a way to record the values of non-constant parameters (e.g., needed for some plots in BioModels), I tried to see if I could use an assignment rule to record the values of non-constant parameters (i.e., assign the value of a parameter to a species).

Example: `dNFAT` (parameter) and `dNFAT_species` (species) in [BIOMD678.xml.txt](https://github.com/PySCeS/pysces/files/7009040/BIOMD678.xml.txt).

However, PySCeS didn't record the value of `dNFAT_species`. One possible hint I see is
```
Info: "dNFAT_species" has been initialised but does not occur in a rate equation
```

I have two questions:
- Is there a direct way to record the values of non-constant parameters?
- Is there a way to record the values of such species set via assignment rules? i.e., is there something else I can do to trigger PySCeS to record their values?

**Comment by jmrohwer** [comment]
This has now been fixed in [Release 1.0.2](https://github.com/PySCeS/pysces/releases/tag/1.0.2). Assignment rules are tracked by default in a simulation with CVODE, and the values are available via `mod.data_sim.getXData()`. Refer to https://pyscesdocs.readthedocs.io/en/latest/userguide_doc.html#simulation-results

The change was implemented in https://github.com/PySCeS/pysces/pull/77/commits/8ebbcb326d205e5818e4a7a350eb645c11d83c0e with additional fixes in https://github.com/PySCeS/pysces/pull/77/commits/e9c4444ae2b525cfb32c1e0192eea4b3e20577fd.
