### ISSUE TITLE
Zenodo release for 1.0.1

### ISSUE THREAD

**Issue by jmrohwer** [PySCeS/pysces#74]
I have released 1.0.1 and the source and wheels are on PyPI and the Anaconda packages are uploaded as well.

I see that the source files for 1.0.1 have been transferred to Zenodo (I assume this is part of an automatic workflow update). However, a new version has not been registered at Zenodo. Under Versions, the most recent one listed is 0.9.8 with a publication date of 13 May 2020 (although the correct source files are there).
https://zenodo.org/record/6260080

@bgoli Could you look into this?

**Comment by bgoli** [comment]
Done. The Zenodo metadata transfer is not completely automatic and needs to be updated by hand, I had to do the 1.0.0 release by hand as the transfer failed due to a configuration error in the CFF file. I've updated the metadata and everything is now in sync [again](https://doi.org/10.5281/zenodo.6260080).
